const countries = [
  { countryCode: 1, regionCode: "US", regionName: "United States" },
  { countryCode: 7, regionCode: "RU", regionName: "Russia" },
  { countryCode: 20, regionCode: "EG", regionName: "Egypt" },
  { countryCode: 27, regionCode: "ZA", regionName: "South Africa" },
  { countryCode: 30, regionCode: "GR", regionName: "Greece" },
  { countryCode: 31, regionCode: "NL", regionName: "Netherlands" },
  { countryCode: 32, regionCode: "BE", regionName: "Belgium" },
  { countryCode: 33, regionCode: "FR", regionName: "France" },
  { countryCode: 34, regionCode: "ES", regionName: "Spain" },
  { countryCode: 36, regionCode: "HU", regionName: "Hungary" },
  { countryCode: 39, regionCode: "IT", regionName: "Italy" },
  { countryCode: 40, regionCode: "RO", regionName: "Romania" },
  { countryCode: 41, regionCode: "CH", regionName: "Switzerland" },
  { countryCode: 43, regionCode: "AT", regionName: "Austria" },
  { countryCode: 44, regionCode: "GB", regionName: "United Kingdom" },
  { countryCode: 45, regionCode: "DK", regionName: "Denmark" },
  { countryCode: 46, regionCode: "SE", regionName: "Sweden" },
  { countryCode: 47, regionCode: "NO", regionName: "Norway" },
  { countryCode: 48, regionCode: "PL", regionName: "Poland" },
  { countryCode: 49, regionCode: "DE", regionName: "Germany" },
  { countryCode: 51, regionCode: "PE", regionName: "Peru" },
  { countryCode: 52, regionCode: "MX", regionName: "Mexico" },
  { countryCode: 53, regionCode: "CU", regionName: "Cuba" },
  { countryCode: 54, regionCode: "AR", regionName: "Argentina" },
  { countryCode: 55, regionCode: "BR", regionName: "Brazil" },
  { countryCode: 56, regionCode: "CL", regionName: "Chile" },
  { countryCode: 57, regionCode: "CO", regionName: "Colombia" },
  { countryCode: 58, regionCode: "VE", regionName: "Venezuela" },
  { countryCode: 60, regionCode: "MY", regionName: "Malaysia" },
  { countryCode: 61, regionCode: "AU", regionName: "Australia" },
  { countryCode: 62, regionCode: "ID", regionName: "Indonesia" },
  { countryCode: 63, regionCode: "PH", regionName: "Philippines" },
  { countryCode: 64, regionCode: "NZ", regionName: "New Zealand" },
  { countryCode: 65, regionCode: "SG", regionName: "Singapore" },
  { countryCode: 66, regionCode: "TH", regionName: "Thailand" },
  { countryCode: 81, regionCode: "JP", regionName: "Japan" },
  { countryCode: 82, regionCode: "KR", regionName: "South Korea" },
  { countryCode: 84, regionCode: "VN", regionName: "Vietnam" },
  { countryCode: 86, regionCode: "CN", regionName: "China" },
  { countryCode: 90, regionCode: "TR", regionName: "Turkey" },
  { countryCode: 91, regionCode: "IN", regionName: "India" },
  { countryCode: 92, regionCode: "PK", regionName: "Pakistan" },
  { countryCode: 93, regionCode: "AF", regionName: "Afghanistan" },
  { countryCode: 94, regionCode: "LK", regionName: "Sri Lanka" },
  { countryCode: 95, regionCode: "MM", regionName: "Myanmar (Burma)" },
  { countryCode: 98, regionCode: "IR", regionName: "Iran" },
  { countryCode: 211, regionCode: "SS", regionName: "South Sudan" },
  { countryCode: 212, regionCode: "MA", regionName: "Morocco" },
  { countryCode: 213, regionCode: "DZ", regionName: "Algeria" },
  { countryCode: 216, regionCode: "TN", regionName: "Tunisia" },
  { countryCode: 218, regionCode: "LY", regionName: "Libya" },
  { countryCode: 220, regionCode: "GM", regionName: "Gambia" },
  { countryCode: 221, regionCode: "SN", regionName: "Senegal" },
  { countryCode: 222, regionCode: "MR", regionName: "Mauritania" },
  { countryCode: 223, regionCode: "ML", regionName: "Mali" },
  { countryCode: 224, regionCode: "GN", regionName: "Guinea" },
  { countryCode: 225, regionCode: "CI", regionName: "Côte d’Ivoire" },
  { countryCode: 226, regionCode: "BF", regionName: "Burkina Faso" },
  { countryCode: 227, regionCode: "NE", regionName: "Niger" },
  { countryCode: 228, regionCode: "TG", regionName: "Togo" },
  { countryCode: 229, regionCode: "BJ", regionName: "Benin" },
  { countryCode: 230, regionCode: "MU", regionName: "Mauritius" },
  { countryCode: 231, regionCode: "LR", regionName: "Liberia" },
  { countryCode: 232, regionCode: "SL", regionName: "Sierra Leone" },
  { countryCode: 233, regionCode: "GH", regionName: "Ghana" },
  { countryCode: 234, regionCode: "NG", regionName: "Nigeria" },
  { countryCode: 235, regionCode: "TD", regionName: "Chad" },
  {
    countryCode: 236,
    regionCode: "CF",
    regionName: "Central African Republic",
  },
  { countryCode: 237, regionCode: "CM", regionName: "Cameroon" },
  { countryCode: 238, regionCode: "CV", regionName: "Cape Verde" },
  { countryCode: 239, regionCode: "ST", regionName: "São Tomé & Príncipe" },
  { countryCode: 240, regionCode: "GQ", regionName: "Equatorial Guinea" },
  { countryCode: 241, regionCode: "GA", regionName: "Gabon" },
  { countryCode: 242, regionCode: "CG", regionName: "Congo - Brazzaville" },
  { countryCode: 243, regionCode: "CD", regionName: "Congo - Kinshasa" },
  { countryCode: 244, regionCode: "AO", regionName: "Angola" },
  { countryCode: 245, regionCode: "GW", regionName: "Guinea-Bissau" },
  {
    countryCode: 246,
    regionCode: "IO",
    regionName: "British Indian Ocean Territory",
  },
  { countryCode: 247, regionCode: "AC", regionName: "Ascension Island" },
  { countryCode: 248, regionCode: "SC", regionName: "Seychelles" },
  { countryCode: 249, regionCode: "SD", regionName: "Sudan" },
  { countryCode: 250, regionCode: "RW", regionName: "Rwanda" },
  { countryCode: 251, regionCode: "ET", regionName: "Ethiopia" },
  { countryCode: 252, regionCode: "SO", regionName: "Somalia" },
  { countryCode: 253, regionCode: "DJ", regionName: "Djibouti" },
  { countryCode: 254, regionCode: "KE", regionName: "Kenya" },
  { countryCode: 255, regionCode: "TZ", regionName: "Tanzania" },
  { countryCode: 256, regionCode: "UG", regionName: "Uganda" },
  { countryCode: 257, regionCode: "BI", regionName: "Burundi" },
  { countryCode: 258, regionCode: "MZ", regionName: "Mozambique" },
  { countryCode: 260, regionCode: "ZM", regionName: "Zambia" },
  { countryCode: 261, regionCode: "MG", regionName: "Madagascar" },
  { countryCode: 262, regionCode: "RE", regionName: "Réunion" },
  { countryCode: 263, regionCode: "ZW", regionName: "Zimbabwe" },
  { countryCode: 264, regionCode: "NA", regionName: "Namibia" },
  { countryCode: 265, regionCode: "MW", regionName: "Malawi" },
  { countryCode: 266, regionCode: "LS", regionName: "Lesotho" },
  { countryCode: 267, regionCode: "BW", regionName: "Botswana" },
  { countryCode: 268, regionCode: "SZ", regionName: "Eswatini" },
  { countryCode: 269, regionCode: "KM", regionName: "Comoros" },
  { countryCode: 290, regionCode: "SH", regionName: "St. Helena" },
  { countryCode: 291, regionCode: "ER", regionName: "Eritrea" },
  { countryCode: 297, regionCode: "AW", regionName: "Aruba" },
  { countryCode: 298, regionCode: "FO", regionName: "Faroe Islands" },
  { countryCode: 299, regionCode: "GL", regionName: "Greenland" },
  { countryCode: 350, regionCode: "GI", regionName: "Gibraltar" },
  { countryCode: 351, regionCode: "PT", regionName: "Portugal" },
  { countryCode: 352, regionCode: "LU", regionName: "Luxembourg" },
  { countryCode: 353, regionCode: "IE", regionName: "Ireland" },
  { countryCode: 354, regionCode: "IS", regionName: "Iceland" },
  { countryCode: 355, regionCode: "AL", regionName: "Albania" },
  { countryCode: 356, regionCode: "MT", regionName: "Malta" },
  { countryCode: 357, regionCode: "CY", regionName: "Cyprus" },
  { countryCode: 358, regionCode: "FI", regionName: "Finland" },
  { countryCode: 359, regionCode: "BG", regionName: "Bulgaria" },
  { countryCode: 370, regionCode: "LT", regionName: "Lithuania" },
  { countryCode: 371, regionCode: "LV", regionName: "Latvia" },
  { countryCode: 372, regionCode: "EE", regionName: "Estonia" },
  { countryCode: 373, regionCode: "MD", regionName: "Moldova" },
  { countryCode: 374, regionCode: "AM", regionName: "Armenia" },
  { countryCode: 375, regionCode: "BY", regionName: "Belarus" },
  { countryCode: 376, regionCode: "AD", regionName: "Andorra" },
  { countryCode: 377, regionCode: "MC", regionName: "Monaco" },
  { countryCode: 378, regionCode: "SM", regionName: "San Marino" },
  { countryCode: 380, regionCode: "UA", regionName: "Ukraine" },
  { countryCode: 381, regionCode: "RS", regionName: "Serbia" },
  { countryCode: 382, regionCode: "ME", regionName: "Montenegro" },
  { countryCode: 383, regionCode: "XK", regionName: "Kosovo" },
  { countryCode: 385, regionCode: "HR", regionName: "Croatia" },
  { countryCode: 386, regionCode: "SI", regionName: "Slovenia" },
  { countryCode: 387, regionCode: "BA", regionName: "Bosnia & Herzegovina" },
  { countryCode: 389, regionCode: "MK", regionName: "North Macedonia" },
  { countryCode: 420, regionCode: "CZ", regionName: "Czechia" },
  { countryCode: 421, regionCode: "SK", regionName: "Slovakia" },
  { countryCode: 423, regionCode: "LI", regionName: "Liechtenstein" },
  {
    countryCode: 500,
    regionCode: "FK",
    regionName: "Falkland Islands (Islas Malvinas)",
  },
  { countryCode: 501, regionCode: "BZ", regionName: "Belize" },
  { countryCode: 502, regionCode: "GT", regionName: "Guatemala" },
  { countryCode: 503, regionCode: "SV", regionName: "El Salvador" },
  { countryCode: 504, regionCode: "HN", regionName: "Honduras" },
  { countryCode: 505, regionCode: "NI", regionName: "Nicaragua" },
  { countryCode: 506, regionCode: "CR", regionName: "Costa Rica" },
  { countryCode: 507, regionCode: "PA", regionName: "Panama" },
  { countryCode: 508, regionCode: "PM", regionName: "St. Pierre & Miquelon" },
  { countryCode: 509, regionCode: "HT", regionName: "Haiti" },
  { countryCode: 590, regionCode: "GP", regionName: "Guadeloupe" },
  { countryCode: 591, regionCode: "BO", regionName: "Bolivia" },
  { countryCode: 592, regionCode: "GY", regionName: "Guyana" },
  { countryCode: 593, regionCode: "EC", regionName: "Ecuador" },
  { countryCode: 594, regionCode: "GF", regionName: "French Guiana" },
  { countryCode: 595, regionCode: "PY", regionName: "Paraguay" },
  { countryCode: 596, regionCode: "MQ", regionName: "Martinique" },
  { countryCode: 597, regionCode: "SR", regionName: "Suriname" },
  { countryCode: 598, regionCode: "UY", regionName: "Uruguay" },
  { countryCode: 599, regionCode: "CW", regionName: "Curaçao" },
  { countryCode: 670, regionCode: "TL", regionName: "Timor-Leste" },
  { countryCode: 672, regionCode: "NF", regionName: "Norfolk Island" },
  { countryCode: 673, regionCode: "BN", regionName: "Brunei" },
  { countryCode: 674, regionCode: "NR", regionName: "Nauru" },
  { countryCode: 675, regionCode: "PG", regionName: "Papua New Guinea" },
  { countryCode: 676, regionCode: "TO", regionName: "Tonga" },
  { countryCode: 677, regionCode: "SB", regionName: "Solomon Islands" },
  { countryCode: 678, regionCode: "VU", regionName: "Vanuatu" },
  { countryCode: 679, regionCode: "FJ", regionName: "Fiji" },
  { countryCode: 680, regionCode: "PW", regionName: "Palau" },
  { countryCode: 681, regionCode: "WF", regionName: "Wallis & Futuna" },
  { countryCode: 682, regionCode: "CK", regionName: "Cook Islands" },
  { countryCode: 683, regionCode: "NU", regionName: "Niue" },
  { countryCode: 685, regionCode: "WS", regionName: "Samoa" },
  { countryCode: 686, regionCode: "KI", regionName: "Kiribati" },
  { countryCode: 687, regionCode: "NC", regionName: "New Caledonia" },
  { countryCode: 688, regionCode: "TV", regionName: "Tuvalu" },
  { countryCode: 689, regionCode: "PF", regionName: "French Polynesia" },
  { countryCode: 690, regionCode: "TK", regionName: "Tokelau" },
  { countryCode: 691, regionCode: "FM", regionName: "Micronesia" },
  { countryCode: 692, regionCode: "MH", regionName: "Marshall Islands" },
  { countryCode: 850, regionCode: "KP", regionName: "North Korea" },
  { countryCode: 852, regionCode: "HK", regionName: "Hong Kong" },
  { countryCode: 853, regionCode: "MO", regionName: "Macao" },
  { countryCode: 855, regionCode: "KH", regionName: "Cambodia" },
  { countryCode: 856, regionCode: "LA", regionName: "Laos" },
  { countryCode: 880, regionCode: "BD", regionName: "Bangladesh" },
  { countryCode: 886, regionCode: "TW", regionName: "Taiwan" },
  { countryCode: 960, regionCode: "MV", regionName: "Maldives" },
  { countryCode: 961, regionCode: "LB", regionName: "Lebanon" },
  { countryCode: 962, regionCode: "JO", regionName: "Jordan" },
  { countryCode: 963, regionCode: "SY", regionName: "Syria" },
  { countryCode: 964, regionCode: "IQ", regionName: "Iraq" },
  { countryCode: 965, regionCode: "KW", regionName: "Kuwait" },
  { countryCode: 966, regionCode: "SA", regionName: "Saudi Arabia" },
  { countryCode: 967, regionCode: "YE", regionName: "Yemen" },
  { countryCode: 968, regionCode: "OM", regionName: "Oman" },
  { countryCode: 970, regionCode: "PS", regionName: "Palestine" },
  { countryCode: 971, regionCode: "AE", regionName: "United Arab Emirates" },
  { countryCode: 972, regionCode: "IL", regionName: "Israel" },
  { countryCode: 973, regionCode: "BH", regionName: "Bahrain" },
  { countryCode: 974, regionCode: "QA", regionName: "Qatar" },
  { countryCode: 975, regionCode: "BT", regionName: "Bhutan" },
  { countryCode: 976, regionCode: "MN", regionName: "Mongolia" },
  { countryCode: 977, regionCode: "NP", regionName: "Nepal" },
  { countryCode: 992, regionCode: "TJ", regionName: "Tajikistan" },
  { countryCode: 993, regionCode: "TM", regionName: "Turkmenistan" },
  { countryCode: 994, regionCode: "AZ", regionName: "Azerbaijan" },
  { countryCode: 995, regionCode: "GE", regionName: "Georgia" },
  { countryCode: 996, regionCode: "KG", regionName: "Kyrgyzstan" },
  { countryCode: 998, regionCode: "UZ", regionName: "Uzbekistan" },
];

export default countries;
