const strings = {
en: {
searchListHeader:"Popular public sources",
FormHelperText:"Search or paste URl’s of Public sources used in your project",
InputPlaceholder:"USA",
radioLabel:"Sole trader",
formLabel:"Publisher ID",
stepperStep:"Address",
noThanksButton:"No thanks ",
toastText:"Data connector removed",
componentHeader:"Uploading ",
editUploadedFileActionText:"Replace",
uploadProgressText:"Uploading file",
uploadFieldHelpText:"The build deployment package is a packaged version of your local build. It must include:Your Prifina App IDA completed Manifest file.Come in a .zip with a maximum file size of [?].Read more on Prifina docs [link]",
sectionStatusText:"Unsaved changes",
cancelButton:"Cancel",
FormLabel:"Version Number",
globalNavLink:"Dashboard",
helpPara:"The build deployment package is a packaged version of your local build. It must include:<li>Your Prifina App ID<li>A completed Manifest file<li>Come in a .zip with a maximum file size of [?]",
sectionHeading:"Build deployment",
InputPlaceholderHeading:"Build deployment package",
helpHeading:"Build deployment package",
InputPlaceholderPara:"Upload a .zip file of your buildDrag and drop a file here or click to upload",
pageHeading:"Project resources",
IntroPara:"Add your .Zip build deployment package and information regarding your apps data usage here to prepare for handoff to a nominated publisher account.",
buttonText:"Remove ",
destructiveButtonText:"Discard changes",
modalPara:"If you navigate away from the page any unsaved changes will be lost.",
modalHeader:"You have unsaved changes",
attributeCountText:"Your project uses",
linkText:"Full spec here",
newProjectButton:"New project",
EmptyStateCTAText:"Done with your local build and ready to plug into the power of Prifina? Create a project to get started",
EmptyStateCTAHeader:"Create your first project",
loadingScreenText:"This may take a few seconds",
acceptButton:" Accept",
notYouLinkText:"Not you? Click here",
bannerGreatNewsText:"Because you have an existing individual Prifina account, you can use it to log in, and we’ll connect it to your new developer account.",
bannerGreatNewsHeader:"Great News!",
bannerAccDetectedText:"We noticed you are currently logged into Prifina as JohnS116",
stepperStep2:"02  Developer Agreement",
stepperStep1:"01  Account Details",
additionalDisclaimer:"Disclaimer message or T&C’s if required Console and its features you will need to create a seperate account. But don’t worry, the process is quick and easy and you can use your existing Prifina account to get setup.",
redirectMessage:"To get access to Prifina’s Developer Console and its features you will need to create a separate account. But don’t worry, the process is quick and easy and you can use your existing Prifina account to get setup.",
redirectMessageHeader:"Redirect necessary",
accountLinkModalHeader:"Create App Studio account",
appNameDataCloud :"Data Cloud ",
appNameSettings :"Settings",
appNameSmartSearch :"Smart Search ",
appNameAppStudio:"Developer Console",
appNameDisplay:"Display",
appNameAppMarketplace:"App Marketplace ",
appNameProfileCards:"Profile cards",
ageAppropriateWeatherly:"3+",
keyFeaturesWeatherly:"Public data display",
widgetDescriptionLongWeatherly:"This simple widget gives you insight into the weather in different locations you choose. You can access it in your account from where ever you access the internet.",
categoryWeatherly:"Weather",
deviceSupportWeatherly:"Desktop browser",
languageSupportWeatherly:"ENG (English)",
highLevelCategoryWeatherly:"Utilities",
dataTypesWeatherly:"User-generated, Public",
widgetNameWeatherly:"Weatherly",
'ageAppropriateTo-do-list':"3+",
'widgetDescriptionLongTo-do-list':"To do's that are always in your Prifina account. Useful for keeping track of lists, and notes for different circumstances, especially where you don't have your own computer to use. No servers or logs keep your notes private and fully under your own control.",
'keyFeaturesTo-do-list':"Tasks and notesTheme customization",
'languageSupportTo-do-list':"ENG (English)",
'deviceSupportTo-do-list':"Desktop browser",
'dataTypesTo-do-list':"User-generated",
'categoryTo-do-list':"Productivity",
'highLevelCategoryTo-do-list':"Utilities",
'widgetNameTo-do-list':"To-do-list",
ageAppropriateBrowserChat:"7+",
keyFeaturesBrowserChat:"Private communicationTheme customization",
widgetDescriptionLongBrowserChat:"Browser chat is really private to you, there is no company between you and the person you are messaging. Messages are sent from your browser-session to the other browser-session, with no servers or logs in between.This all is to say you are in control. You choose what you record and what you don't.",
deviceSupportBrowserChat:"Desktop browser",
languageSupportBrowserChat:"ENG (English)",
categoryBrowserChat:"Communication",
dataTypesBrowserChat:"User-generated, No Data",
highLevelCategoryBrowserChat:"Staff Pick",
'widgetNameBrowserTo-do-list':"Browser Chat",
ageAppropriateBattleship:"3+",
widgetDescriptionLongBattleship:"This app allows users to play a relatively simple game, while showcasing functionality for developers such as peer to peer connectivity, helping model future applications.",
keyFeaturesBattleship:"Play contactsPlay next available",
languageSupportBattleship:"ENG (English)",
deviceSupportBattleship:"Desktop browser",
dataTypesBattleship:"No Data",
highLevelCategoryBattleship:"Staff Pick",
categoryBattleship:"Games",
widgetNameBattleship:"Battleship",
keyFeaturesAnonSearch:"Anonymous searchAggregated results",
ageAppropriateAnonSearch:"7+",
widgetDescriptionLongAnonSearch:"Forget cookies and meta tags - Power to the people with Search. You yourself control what information, if any, you use while searching.Search the Internet without revealing any data about yourself. Or search the Internet using a certain "role", such as your work role or your personal role. You decide, no one else.",
languageSupportAnonSearch:"ENG (English)",
deviceSupportAnonSearch:"Desktop browser",
dataTypesAnonSearch:"User-generated, No Data",
categoryAnonSearch:"Productivity",
highLevelCategoryAnonSearch:"Staff Pick",
widgetNameAnonSearch:"Anon search",
ageAppropriateDataUploader:"7+",
 keyFeaturesDataUploader:"Upload dataConnect sources",
widgetDescriptionLongDataUploader:"Bring your own data. Upload datasets to activate different Prifina apps. Start off by testing your location date, which you can get from Google Takeout (",
languageSupportDataUploader:"ENG (English)",
categoryDataUploader:"Prifina tools",
deviceSupportDataUploader:"Desktop browser",
highLevelCategoryDataUploader:"Utilities",
dataTypesDataUploader:"User-held",
widgetNameDataUploader:"Data uploader",
AppropriateCarbonFootprint:"12+",
languageSupportCarbonFootprint:"ENG (English)",
categoryCarbonFootprint:"Lifestyle",
keyFeaturesCarbonFootprint:"View CO2 impactOffset CO2 generatedLocal data - use data without sharing externally",
deviceSupportCarbonFootprint:"Desktop browser",
dataTypesCarbonFootprint:"User-held, User-generated, Public",
widgetDescriptionLongCarbonFootprint:"The Carbon Footprint widget helps you quantify and offset your environmental impact when moving about. This widget helps you track your carbon load on the planet and suggests simple ways to neutralize it.By utilizing your location data, the Carbon Footprint widget can how you've traveled (car, bike, train etc) and use approximate public data to calculate carbon offset for the mode of transportation.When this calculation is done, the widget will show you how much CO2 this activity can have generated and suggest ways to offset the carbon impact.",
highLevelCategory CarbonFootprint:"Cloud powered (change if you like)",
dataAlertTextCarbonFootprint:"This app requires location data to run",
widgetNameCarbonFootprint:"Carbon Footprint",
languageSupportDryRun:"ENG (English)",
 ageAppropriateDryRun:"12+",
categoryDryRun:"Health & Fitness",
deviceSupportDryRun:"Desktop browser",
dataTypesDryRun:"User-held, User-generated",
widgetDescriptionLongDryRun:"Dry Run wants to keep you dry while you exercise. By utilizing your activity habits and open weather data, Dry Run looks out for you and lets you know when it might make sense to deviate from your normal routines. Planned updates for Dry Run include utilizing other weather data types, such as allergens, air quality or pollen.",
keyFeaturesDryRun:"Personalized activity scheduling suggestions",
dataAlertTextDryRun:"This widget needs activity data to run",
highLevelCategory DryRun:"Data on your side",
widgetNameDryRun:"Dry Run",
 ageAppropriateSleepwell:"7+",
languageSupportSleepwell:"ENG (English)",
categorySleepwell:"Health & Fitness",
deviceSupportSleepwell:"Desktop browser",
keyFeaturesSleepwell:"Sleep analysis and insightsLocal data - use your data with no external sharing",
widgetDescriptionLongSleepwell:"What impacts your sleep? Do you sleep better after a comedy filled evening on Netflix or maybe its documentaries that really relax your mind? With the Sleepwell widget, you can compare your streaming habits to your deep sleep and get insights into your own sleep patterns. In the future, this widget can expand to more personalized suggestions and different data types, all in order to deliver you the best ZZZs",
highLevelCategorySleepwell:"Data on your side",
dataTypesSleepwell:"User-held",
dataAlertTextSleepwell:"This widget requires sleep data to run",
widgetNameSleepwell:"Sleepwell",
languageSupportHolisticHealth:"ENG (English)",
ageAppropriateHolisticHealth:"12+",
categoryHolisticHealth:"Health & Fitness",
deviceSupportHolisticHealth:"Desktop browser",
keyFeaturesHolisticHealth:"Snapshot of Activity ProgressLocal data - use your data without external sharing",
dataTypesHolisticHealth:"User-held",
widgetDescriptionLongHolisticHealth:"With Holistic Health, you can track your activity from all your wearables in one place, see what targets you have hit and view a snapshot of your daily goals. Utilizing your activity data (active minutes, steps, calories etc) from your wearable devices, you can quickly for an idea of your progress toward your goals and keep yourself accountable.",
dataAlertTextHolisticHealth:"This app needs activity data to run",
highLevelCategoryHolisticHealth :"Data on your side",
widgetNameHolisticHealth:"Holistic Health",
ageAppropriateClock:"3+",
deviceSupportClock:"Desktop browser",
languageSupportClock:"ENG (English)",
categoryClock:"Productivity",
keyFeaturesClock:"Time displayMultiple timezones",
widgetDescriptionLongClock:"Set important timezones for you to follow or simply keep track of the time next to other widgets you use. This simple clock widget exists in your Prifina account and is accessible from where ever you use the Internet.",
dataTypesClock:"User-generated, Public",
highLevelCategoryClock:"Utilities",
widgetNameClock:"Clock",
widgetDescriptionShortWeatherly:"Heads up widget for showing you the weather in relevant locations to you.",
widgetDescriptionShortDataUploader:"Upload and activate your data. Easily upload documents, images and other files into your personal data cloud. Then utilize this data in your personal applications, for personal value.",
'widgetDescriptionShortTo-do-list':"Forgetting your sticky notes? Keep your to-do lists synchronized across any device, including any devices you only borrow.",
widgetDescriptionShortClock:"The clock widget displays allows you to compare the time in four separate locations.",
 widgetDescriptionShortClock:"The clock widget displays allows you to compare the time in four separate locations.",
widgetDescriptionShortAnonSearch:"Search the Internet without revealing any data about yourself. A truly private search widget allows private searches or searches which only you can remember.",
widgetDescriptionShortBattleship:"A peer to peer game without any servers demonstrates gaming logic and allows you to play battleship with contacts in your contact book or random participants.",
widgetDescriptionBrowserChat:"The Browser Chat widget is a true peer to peer application that allows private chats without any logs. Choose what is stored and what disappears in your chat, without anyone in between.",
widgetDescriptionShortCarbon footprint:"Quantify and offset your environmental impact when driving about. This widget helps you track your carbon load on the planet and suggests simple ways to neutralize it.",
widgetDescriptionShortHolistic health:"Track your activity from all your wearables in one place, see what targets you have hit and view a snapshot of your daily goals.",
widgetDescriptionShortDryRun:"Tired of running in bad weather? With Dry Run, utilize your activity data and you get a heads up when your typical time for a run collides with a sleet or a tropical storm.",
widgetDescriptionShortSleepwell:"What makes a good night's sleep? What movie gives you the best ZZZs? This Sleep Quality widget compares your daily streaming activities and their impact on your sleep quality.",
'Featured widgets section - paragraph text':"This section features all the widgets which require user-held data",
'Featured widgets section - header text':"Data on your side",
AnnouncementBannerHeaderText:"Data on your side",
Announcement banner paragraph text:"Free your data from its silos and utilize it in different apps and widgets. Like a key, your data can unlock valuable experiences and insights. By using your data directly, you capture the value and open a new market of apps.",
createNewPubAcc:"Create a new publisher account",
saveButton:"Save",
noDataCalloutText:"A ‘no data’ project does not pull any data from any source.",
noDataCheckboxText:"My project does not require any data to run.",
dataSourceListEmptyStateText:"Data sources you add will show up here.",
dataSourceListEmptyStateHeading:"Search and select data sources",
dataSourceListHeading:"Data sources used in your project",
tabText:"Public Source",
appBranding:"App Studio",
pubAccEmptyStateText:"Yet to be defined ",
pubAccEmptyStateTitle:"Create , Invite , Publish",
'soleTraderIn-pageNotificationText':"Somebody who is self-employed but is also the exclusive owner of their business.",
formHeading:"Create publisher account",
createAccButton:"Create account",
CreatePubAccCTAText:"Ready to release your project to the world? Create a publisher account to get started.",
CreatePubAccCTATitle:"Publisher account",
prifinaDocsLink:"Read more on Prifina docs",
logoutTitle:"Are you sure you want to sign out?",
sentCodeText:"We have sent you a code to your phone number and email address to reset your password.",
resetPasswordText:"Enter your username. We will send you a confirmation code to reset your password.",
newPassword:"New password",
resetPasswordTitle:"Reset password code",
loginPage:"Login to your account",
declineTitle:"Decline Prifina’s Terms of Use?",
authConfirmTitle:"Enter authentication code",
forgotUsername:"Forgot username?",
confirmTitle:"Secure login",
useEmail:"Do you want to use your email adress?",
invalidLogin:"Incorrect username or password.",
emailVerificationTitle:"Setup email verification",
confirmationCodeSent:"Authentication code was sent to your vefified phone number.",
resetPasswordText3:"Your password has been reset. Please login with your new password.",
recoverUsernameText2:"If a user account with that phone number exists, we have sent a username to that number.",
logoutText:"You are also logged out from your personal cloud and any local data apps open in this browser.",
recoverUsernameTitle:"Recover username",
recoverUsernameText1:"Enter your phone number. We will send you a confirmation code to recover your username.",
sendAgainLinkText2:"Click here to resend.",
resetPasswordText2:"Please check your phone or email for your verification code. Your code is six digits long. Complete the fields below to reset your password.",
forgotPassword:"Forgot password?",
emailVerificatioSent:"Email verification code was sent.",
authConfirmationText:"We've sent you the authentication code. Please enter it below to login.",
emailMissing:"Didn't receive the code?",
doneButton:"Done",
confirmNewPassword:"Confirm new password",
declineText:"By declining Prifina's Terms of Use you will not be able to use the Prifina application.",
forgotUsername2:"Forgot your username?",
codeMissing2:"Did not receive your code?",
createAccount:"Create account",
emailVerificationText:"Please provide your email address and phone number to keep your account secure",
codeLengthError:"The code must be six digits long",
accountsText:"To access Prifina’s Services, you will need to create an account (“Account”).",
dataText:"Your data is fully under your control. Only you can access your data and your data profiles. Third parties can access your data only with your permission.",
codeMissing:"Didn't receive the code?",
invalidCode:"Incorrect code, please enter the correct code.",
agreementText:"By using or visiting any of Prifina’s websites, or any of our products, software, or applications, you signify your agreement to these Terms.",
codeDigitsError:"Only numbers are allowed",
phoneVerificatioSent:"Phone number verification code was sent.",
serviceText:"Some of the things you can do through the Service are listed below.",
codePropmt:"Enter the code here",
materialsText:"Certain portions of the Service may include, display, or make available content, data, information, applications, or materials from third parties (“Third-Party Materials”).",
verificationTitle:"Setup your two-step verification method",
agreeementTitle:"Agreement",
termsLastUpdated:"Last updated: October, 2020",
phoneVerificationText:"Please provide your email address and phone number in order to keep your account secure",
sendAgainLinkText:"Click here.",
dataTitle:"Your Data",
accountsTitle:" ",
phoneVerificationTitle:"Setup your phone verification",
materialsTitle:"Third Party Materials",
verifySUpportLink:"Still didn't receive the code",
termsTitle:"Prifina's Terms of Use",
landingPageInfo:"Fill in the form on the right",
loginWelcomeMessage:"My Prifina",
welcomeMessage:"Hello",
landingPage:"We are a team working on the future of personal applications. That's why we created this personal cloud environment that will help you implement your boldest ideas while allowing individuals to keep their data.",
serviceTitle:"The Service",
loginLandingPage:"Login to access your personal data cloud.",
acceptTerms:"Please approve terms of use to continue.",
usernamePlaceholder:"Username",
passwordPlaceholder:"Password",
lastNamePlaceholder:"Last Name",
invalidEntry:"Value is required",
confirmPlaceholder:"Confirm Password",
invalidPassword:"Password confirmation failed",
emailPrompt:"This email will be used for two-step verification.",
existingAccount:"Have an account?",
phoneNumberPlaceholder2:"555_555_555",
usernameExists:"Invalid username.",
passwordQuality:"Password conditions failed",
finalizeText:"This process may take a few seconds",
invalidPhoneNumber:"Invalid or existing phone number",
usernameError:"Username is too short (under {{length}} characters)",
invalidRegion:"Select region code",
phoneNumberPlaceholder:"Phone Number",
phonePrompt:"This number will be used for two-step verification.",
firstNamePlaceholder:"First Name",
invalidEmail:"Invalid or existing email",
createAccountTitle:"Create an account",
emailPlaceholder:"Email",
usernameError2:"Spaces are not allowed in the username",
nextButton:"Next",
loginLink:"Login",
approveButton:"Approve",
confirmButton:"Confirm",
backButton:"Back",
registerButton:"Register",
signInButton:"Sign In",
logoutButton:"Logout",
verifyButton:"Verify",
declineButton:"Decline",
loginButton:"Login",
accountButton:"Creating account",
}};
export default { ...strings };
